export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	SET_CATEGORIES: 'SET_CATEGORIES',
	REMOVE_CATEGORY: 'REMOVE_CATEGORY',
	SET_CATEGORY: 'SET_CATEGORY',
	SET_OPERATIONS: 'SET_OPERATIONS',
	SET_OPERATION: 'SET_OPERATION',
	REMOVE_OPERATION: 'REMOVE_OPERATION',
	SET_ACCOUNTS: 'SET_ACCOUNTS',
	SET_ACCOUNT: 'SET_ACCOUNT',
	REMOVE_ACCOUNT: 'REMOVE_ACCOUNT',
	SET_LAST_DATE: 'SET_LAST_DATE',
	LOGOUT: 'LOGOUT',
};
